name: flutter_wilayah_indonesia
description: Cascading Indonesian regions (Prov/Kab/Kec/Kel) with offline JSON, caching, and ready-to-use WilayahPicker widget.
version: 0.1.0

homepage: https://github.com/normndakbr/flutter_wilayah_indonesia
repository: https://github.com/normndakbr/flutter_wilayah_indonesia
issue_tracker: https://github.com/normndakbr/flutter_wilayah_indonesia/issues
topics:
  - indonesia
  - address
  - wilayah

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^1.5.0

flutter:
  assets:
    - assets/wilayah/provinsi.json
    - assets/wilayah/kabupaten.json
    - assets/wilayah/kecamatan.json
    - assets/wilayah/kelurahan.json
